version: '3.8'

services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/logs/:/var/logs/nginx/
        ports:
            - "8085:8085"
        depends_on:
            - app

    app:
        container_name: app
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        env_file: ./docker/app.env
        volumes:
            - ./:/var/www/html
        depends_on:
            - db

    db:
        container_name: db
        image: postgres:16.1-alpine3.19
        restart: always
        env_file: ./docker/app.env
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -q -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
            interval: 5s
            retries: 5

    init:
        container_name: init
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        env_file: ./docker/app.env
        volumes:
            - ./:/var/www/html
        command: bash -c "chmod +x ./docker/run.sh && ./docker/run.sh"
        depends_on:
            db:
                condition: service_healthy
