version: '3'

services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./:/var/www/film-catalog
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/logs/:/var/logs/nginx/
        ports:
            - "8085:8085"
        depends_on:
            - app

    app:
        container_name: app
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/film-catalog
        depends_on:
            - db

    db:
        container_name: db
        image: postgres:16.1-alpine3.19
        restart: always
        environment:
            POSTGRES_USER: filmcatalog
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: film-catalog
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
